clearvars
close all

t=0:0.01:20; 
rng(1234); 
X=1.5+cos(3*t)-0.25*sin(0.5*t)+0.2*rand(1,length(t)); 

rangeTime = [10.5, 11.5];              % rangeTime, for item (a)
tempS25 = 10.33;                       % for item (b)
timeTickIndNodHint3 = 255;             % for item (c)

clc
fprintf('\t\tReavaluació 04-07-2023 Problema 2\n\n')
%
% Item (a)
% 
indRange = find(t >= rangeTime(1,1) & t <= rangeTime(1,2));
minXatGivemTimeRange = min(X(indRange));
minXatGivemTimeRangeAlt = min(X(t >= 10.499 & t < 11.501)); % Alternatively...
maxX = max(X); % Hint 1

fprintf(['(a) The minimum value of the signal on the time interval\n', ...
         '    [%.1f, %.1f] is: %.4e (%.4e)\n', ...
         '     Hint 1. The maximum value of the signal X on the whole\n', ...
         '             interval [%.1f, %.1f] is: %.4e\n\n'], ...
         rangeTime, ...
         minXatGivemTimeRange, ...
         minXatGivemTimeRangeAlt, ...
         t(1), ...
         t(end), ...
         maxX ...
         )
%
% Item (b)
%
X25 = X(1:25:end);
t25 = t(1:25:end);
xs25t25 = spline(t25, X25, tempS25);
max_xs25 = max(spline(t25, X25, t));   % Hint 2

fprintf(['(b) The the value of this spline on the time t = %.2f,\n', ...
         '    is s25(%.2f) is : %.4e\n', ...
         '    Hint 2. The maximum value of the spline s25 over all the\n', ...
         '            time ticks is %.4e\n\n'], ...
         tempS25, ...
         tempS25, ...
         xs25t25, ...
         max_xs25 ...
         )
%
% Item (c)
%
err = norm(X-spline(t25, X25, t), 'inf');
errTimeTickNodHint3 = abs(X(255)-spline(t25, X25, t(timeTickIndNodHint3)));

fprintf(['(c) The maximum value of the spline s25 over all the\n', ...
         '    time ticks is: %.4e\n', ...
         '    Hint 3. The absolute difference between the signal and\n', ...
         '            the spline at the time tick %d is: %.4e\n\n'], ...
         err, ...
         timeTickIndNodHint3, ...
         errTimeTickNodHint3 ...
         )







